### ISSUE TITLE
undefined method `[]' for nil:NilClass

### ISSUE THREAD

**Issue by qsona** [kenjiszk/remote_attr_accessor#4]
https://github.com/kenjiszk/remote_attr_accessor/blob/master/lib/remote_attr_accessor/attrs.rb#L14
For example, the remote_key is `users` and we expect that the remote api returns `{ 'users' => { '1' => { foo: 1 } } }`
But if remote api returns `{ 'users' => { } }`, the following error occurs

NoMethodError - undefined method `[]' for nil:NilClass:
 remote_attr_accessor (0.0.2) lib/remote_attr_accessor/attrs.rb:14:in`block (2 levels) in module:Attrs'

**Comment by kenjiszk** [comment]
Return nil or skip if remote user is not exist.
https://github.com/kenjiszk/remote_attr_accessor/pull/7/files
